DROP TABLE IF EXISTS DIGITADORDB;
 
CREATE TABLE DIGITADORDB (
  IDDIGITADOR INT AUTO_INCREMENT  PRIMARY KEY,
  MATRICULA VARCHAR(250) NOT NULL,
  NOME VARCHAR(250) NOT NULL,
  TIPO VARCHAR(250) NOT NULL,
  ESCRITO VARCHAR(250) DEFAULT NULL,
  DATATRABALHO VARCHAR(250) DEFAULT NULL
);
 
INSERT INTO DIGITADORDB (IDDIGITADOR, MATRICULA, NOME, TIPO, ESCRITO, DATATRABALHO) VALUES
  (1,'111', 'CARLOS AUGUSTO NUNES','Designação', 'MANUSCRITO - HISTÓRIA MEDIEVAL','25/03/1994'),
  (2,'112', 'ANA CARLA TAVARES','Dispensa', 'MONOGRAFIA - CONCLUSÃO DE CURSO DE DIREITO','25/03/1996'),
  (3,'113', 'ANDREIA GARCIA ALVES','Dispensa', 'DISSERTAÇÃO SOBRE O PERÍODO GLACIAL','25/03/1999');